[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
latest_bls = "E4LXwvzGcZzdJfURbdLDW2BLqz73JLq9ncBd6NteYik"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
